#! /bin/sh -
set -x
cd /home/tangbq/tjs.shop
git pull origin test
rsync -zvrt custom/ root@192.168.3.181:/data/www/ecstore/custom/ 
rsync -zvrt custom/ root@192.168.3.182:/data/www/ecstore/custom/ 
rsync -zvrt app/tiens/ root@192.168.3.181:/data/www/ecstore/app/tiens/
rsync -zvrt app/tiens/ root@192.168.3.182:/data/www/ecstore/app/tiens/
rsync -zvrt public/ root@192.168.3.181:/data/www/ecstore/public/
rsync -zvrt public/ root@192.168.3.182:/data/www/ecstore/public/
cd -
set +x
