#! /bin/bash

cd /work/libs/nginx-1.9.9/conf/vhost/
rm *.conf -rf
ln -s /work/d/code/phpcms.tiens.com/nginx.htaccess                  tiens_phpcms_alllengend.conf
ln -s /work/d/code/www.tiens.com/nginx.htaccess                     tiens_www.conf
ln -s /work/d/code/tjtjs-ecstore/nginx.access                       tiens_testshop_taijisun.conf
ln -s /work/d/code/tiens_hualang/nginx.htaccess                     tiens_hualang.conf
ln -s /work/d/code/yii2apps/appbackend/nginx.htaccess               yii_appbackend.conf
ln -s /work/d/code/yii2apps/appblog/nginx.htaccess                  yii_appblog.conf
ln -s /work/d/code/yii2apps/appfrontend/nginx.htaccess              yii_appfrontend.conf
#ln -s /work/d/code/yii2apps/apptiensmq/nginx.htaccess apptiensmq.conf
ln -s /work/d/tbqapp2/php/ci/apps/www/nginx.htaccess                cidev.conf
ln -s /work/d/tbqapp2/php/chentu.info.wp/nginx.htaccess             wp_chentu_info.conf
ln -s /work/d/tbqapp2/php/tbq.com/apps/tiens_mq/nginx.htaccess      khn_tiens_mq.conf
ln -s /work/d/code/koseven/apps/chentublog/nginx.htaccess           khn_chentublog.conf
ln -s /work/d/code/koseven/apps/www/nginx.htaccess                  khn_www.conf
ln -s /work/d/code/tbq_static/nginx.htaccess                        static.conf
cd -

cd /work/libs/php-5.3.29/var/log
ln -s /work/d/docker_php_log/php-fpm.53.log php-fpm.log
cd -

cd /work/libs/php-5.6.21/var/log
ln -s /work/d/docker_php_log/php-fpm.57.log php-fpm.log
cd -

cd /work/libs/php-7.1.6/var/log
ln -s /work/d/docker_php_log/php-fpm.71.log php-fpm.log
cd -

/work/libs/php-7.1.6/sbin/php-fpm
/work/libs/php-5.6.21/sbin/php-fpm
/work/libs/php-5.3.29/sbin/php-fpm
/work/libs/nginx-1.9.9/sbin/nginx

#/etc/init.d/crond restart
/bin/bash
