<?php
class Controller extends Controller_Core {
	// Default to do auto-rendering
	public $auto_render = TRUE;
	protected $data = array ();
	protected $myjavascripts = array ();
	protected $template = NULL;
	public $themes = '';
	
	public function __construct() {
		parent::__construct ();
		
		$this->MUser = new User_Model ( );
		$this->MSearch = new Search_Model ( );
		$this->MArticle = new Article_Model ( );
		$this->MCategory = new Category_Model ( );
		$this->pagination = new Pagination ( );
		
		$this->session = Session::instance ();
		//$this->encrypt = new Encrypt ( );
	}
	
	/**
	 * Render the loaded template.
	 */
	public function _render() {
		if ($this->auto_render == TRUE) {
			// Render the template when the class is destroyed
			$this->template->render ( TRUE );
		}
	}
	
	protected function setData($varName, $varValue) {
		$this->data [$varName] = $varValue;
	}
	
	protected function dataToTemplate() {
		foreach ( $this->data as $key => $value ) {
			$this->template->$key = $value;
		}
	}
	
	protected function addjs($jsname) {
		array_push ( $this->myjavascripts, $jsname );
	}
	
	public function __call($method, $arguments) {
		// Disable auto-rendering
		$this->auto_render = FALSE;
		
		// By defining a __call method, all pages routed to this controller
		// that result in 404 errors will be handled by this method, instead of
		// being displayed as "Page Not Found" errors.
		echo 'This text is generated by __call. If you expected the index page, you need to use: welcome/index/' . substr ( Router::$current_uri, 8 );
	}
	
	protected function clean($string) {
		return $this->input->xss_clean ( $string );
	}
	
	protected function post($string) {
		return $this->input->post ( $string );
	}
	
	function message($message, $redirectURL) {
		$this->setData ( "message", $message );
		$this->setData ( "redirectURL", $redirectURL );
		$this->template = new View ( "admin/message" );
        $this->dataToTemplate ();
	}
}