-- MySQL Script generated by MySQL Workbench
-- 10/28/14 10:30:39
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rssreader
-- -----------------------------------------------------
-- rss reader
CREATE SCHEMA IF NOT EXISTS `rssreader` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `rssreader` ;

-- -----------------------------------------------------
-- Table `rssreader`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssreader`.`register` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` CHAR(32) NOT NULL,
  `register_time` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '注册用户';


-- -----------------------------------------------------
-- Table `rssreader`.`rss`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssreader`.`rss` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(255) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL DEFAULT '',
  `last_fetchtime` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上次更新时间',
  `createtime` INT UNSIGNED NOT NULL,
  `create_register_id` INT UNSIGNED NOT NULL COMMENT '创建此rss的register id',
  PRIMARY KEY (`id`),
  INDEX `fk_rss_url_register1_idx` (`create_register_id` ASC),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  CONSTRAINT `fk_rss_url_register1`
    FOREIGN KEY (`create_register_id`)
    REFERENCES `rssreader`.`register` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rssreader`.`rss_url_has_register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssreader`.`rss_url_has_register` (
  `rss_url_id` INT UNSIGNED NOT NULL,
  `register_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`rss_url_id`, `register_id`),
  INDEX `fk_rss_url_has_register_register1_idx` (`register_id` ASC),
  INDEX `fk_rss_url_has_register_rss_url_idx` (`rss_url_id` ASC),
  CONSTRAINT `fk_rss_url_has_register_rss_url`
    FOREIGN KEY (`rss_url_id`)
    REFERENCES `rssreader`.`rss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rss_url_has_register_register1`
    FOREIGN KEY (`register_id`)
    REFERENCES `rssreader`.`register` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rssreader`.`rss_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssreader`.`rss_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `link` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '原文链接',
  `title` VARCHAR(255) NOT NULL DEFAULT '',
  `description` TEXT NULL,
  `rss_url_id` INT UNSIGNED NOT NULL DEFAULT 0,
  `author` VARCHAR(255) NOT NULL DEFAULT '',
  `category` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '<category>天下杂谈</category>',
  `comments` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '<comments>http://blog.sina.com.cn/s/blog_3f00a8c20102vbt2.html#comment</comments>',
  `pubdate` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '发布日期,UNIX时间戳',
  `guid` VARCHAR(255) NOT NULL DEFAULT '' COMMENT ' <guid>http://blog.sina.com.cn/s/blog_3f00a8c20102vbt2.html</guid>',
  `fetch_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '取rss的时间',
  PRIMARY KEY (`id`),
  INDEX `fk_rss_detail_rss_url1_idx` (`rss_url_id` ASC),
  UNIQUE INDEX `link_UNIQUE` (`link` ASC),
  CONSTRAINT `fk_rss_detail_rss_url1`
    FOREIGN KEY (`rss_url_id`)
    REFERENCES `rssreader`.`rss` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci
COMMENT = '从rss取到的内容';


-- -----------------------------------------------------
-- Table `rssreader`.`register_read_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rssreader`.`register_read_history` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `read_time` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已读历史,',
  `rss_item_id` INT UNSIGNED NOT NULL,
  `register_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_register_read_history_rss_item1_idx` (`rss_item_id` ASC),
  INDEX `fk_register_read_history_register1_idx` (`register_id` ASC),
  CONSTRAINT `fk_register_read_history_rss_item1`
    FOREIGN KEY (`rss_item_id`)
    REFERENCES `rssreader`.`rss_item` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_register_read_history_register1`
    FOREIGN KEY (`register_id`)
    REFERENCES `rssreader`.`register` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
