package com.yuqi.shop.entity;

// Generated 2010-3-10 22:55:33 by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.yuqi.base.entity.User;

/**
 * ShopItem generated by hbm2java
 */
@Entity
@Table(name = "shop_item", catalog = "yuqiapp_java")
public class Item implements java.io.Serializable {

	private static final long serialVersionUID = -4524496746965707570L;
	private Long id;
	private User user;
	private Category category;
	private String name;
	private String img;
	private String description;
	private float price;
	private Date createTime;

	public Item() {
	}

	public Item(User user, Category category, String name,
			String img, float price, Date createTime) {
		this.user = user;
		this.category = category;
		this.name = name;
		this.img = img;
		this.price = price;
		this.createTime = createTime;
	}

	public Item(User user, Category category, String name,
			String img, String description, float price, Date createTime) {
		this.user = user;
		this.category = category;
		this.name = name;
		this.img = img;
		this.description = description;
		this.price = price;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@Column(name = "name", nullable = false, length = 511)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "img", nullable = false, length = 511)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
