package com.yuqishop.entity;

// Generated 2010-3-10 22:55:33 by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ShopItem generated by hbm2java
 */
@Entity
@Table(name = "shop_item", catalog = "yuqiapp_java")
public class ShopItem implements java.io.Serializable {

	private Long id;
	private SsUser ssUser;
	private ShopCategory shopCategory;
	private String name;
	private String img;
	private String description;
	private float price;
	private Date createTime;

	public ShopItem() {
	}

	public ShopItem(SsUser ssUser, ShopCategory shopCategory, String name,
			String img, float price, Date createTime) {
		this.ssUser = ssUser;
		this.shopCategory = shopCategory;
		this.name = name;
		this.img = img;
		this.price = price;
		this.createTime = createTime;
	}

	public ShopItem(SsUser ssUser, ShopCategory shopCategory, String name,
			String img, String description, float price, Date createTime) {
		this.ssUser = ssUser;
		this.shopCategory = shopCategory;
		this.name = name;
		this.img = img;
		this.description = description;
		this.price = price;
		this.createTime = createTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "creator", nullable = false)
	public SsUser getSsUser() {
		return this.ssUser;
	}

	public void setSsUser(SsUser ssUser) {
		this.ssUser = ssUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id", nullable = false)
	public ShopCategory getShopCategory() {
		return this.shopCategory;
	}

	public void setShopCategory(ShopCategory shopCategory) {
		this.shopCategory = shopCategory;
	}

	@Column(name = "name", nullable = false, length = 511)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "img", nullable = false, length = 511)
	public String getImg() {
		return this.img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

}
