package com.yuqishop.entity;

// Generated 2010-3-10 22:55:33 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShopCategory generated by hbm2java
 */
@Entity
@Table(name = "shop_category", catalog = "yuqiapp_java")
public class ShopCategory implements java.io.Serializable {

	private Long id;
	private ShopCategory shopCategory;
	private String name;
	private Set<ShopCategory> shopCategories = new HashSet<ShopCategory>(0);
	private Set<ShopItem> shopItems = new HashSet<ShopItem>(0);

	public ShopCategory() {
	}

	public ShopCategory(String name) {
		this.name = name;
	}

	public ShopCategory(ShopCategory shopCategory, String name,
			Set<ShopCategory> shopCategories, Set<ShopItem> shopItems) {
		this.shopCategory = shopCategory;
		this.name = name;
		this.shopCategories = shopCategories;
		this.shopItems = shopItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid")
	public ShopCategory getShopCategory() {
		return this.shopCategory;
	}

	public void setShopCategory(ShopCategory shopCategory) {
		this.shopCategory = shopCategory;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopCategory")
	public Set<ShopCategory> getShopCategories() {
		return this.shopCategories;
	}

	public void setShopCategories(Set<ShopCategory> shopCategories) {
		this.shopCategories = shopCategories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "shopCategory")
	public Set<ShopItem> getShopItems() {
		return this.shopItems;
	}

	public void setShopItems(Set<ShopItem> shopItems) {
		this.shopItems = shopItems;
	}

}
