package com.yuqishop.entity;

// Generated 2010-3-10 22:55:33 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * SsResource generated by hbm2java
 */
@Entity
@Table(name = "ss_resource", catalog = "yuqiapp_java", uniqueConstraints = @UniqueConstraint(columnNames = "value"))
public class SsResource implements java.io.Serializable {

	private Long id;
	private double position;
	private String resourceType;
	private String value;

	public SsResource() {
	}

	public SsResource(double position, String resourceType, String value) {
		this.position = position;
		this.resourceType = resourceType;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "position", nullable = false, precision = 22, scale = 0)
	public double getPosition() {
		return this.position;
	}

	public void setPosition(double position) {
		this.position = position;
	}

	@Column(name = "resource_type", nullable = false)
	public String getResourceType() {
		return this.resourceType;
	}

	public void setResourceType(String resourceType) {
		this.resourceType = resourceType;
	}

	@Column(name = "value", unique = true, nullable = false)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
