<?php
return array (
  9 => 
  array (
    'catid' => '9',
    'siteid' => '2',
    'type' => '0',
    'modelid' => '12',
    'parentid' => '0',
    'arrparentid' => '0',
    'child' => '0',
    'arrchildid' => '9',
    'catname' => 'catetest1',
    'style' => '',
    'image' => '',
    'description' => 'catetest1',
    'parentdir' => '',
    'catdir' => 'catetest1',
    'url' => 'http://phpcms.devtest.cn/html/catetest1/',
    'items' => '1',
    'hits' => '0',
    'setting' => '{"workflowid":"","ishtml":"1","content_ishtml":"1","create_to_html_root":"0","template_list":"default.dev","category_template":"category","list_template":"list","show_template":"show","meta_title":"","meta_keywords":"","meta_description":"","presentpoint":"1","defaultchargepoint":"0","paytype":"0","repeatchargedays":"1","category_ruleid":"1","show_ruleid":"11"}',
    'listorder' => '9',
    'ismenu' => '1',
    'sethtml' => '0',
    'letter' => 'catetest1',
    'usable_type' => ',57,',
    'create_to_html_root' => '0',
    'ishtml' => '1',
    'content_ishtml' => '1',
    'category_ruleid' => '1',
    'show_ruleid' => '11',
    'workflowid' => '',
    'isdomain' => '0',
  ),
);
?>